### ISSUE TITLE
[ISSUE]: FreeMcBoot-Installer compilation error

### ISSUE THREAD

**Issue by xbox1978** [israpps/FreeMcBoot-Installer#40]
### Checks

- [ ] I have checked [__existing issues__](https://github.com/israpps/FreeMcBoot-Installer/issues) for duplicates and found none
- [ ] I am using a build downloaded from [this repository](https://israpps.github.io/FreeMcBoot-Installer/test/8_Downloads.html)

### Describe the issue

![Image](https://github.com/user-attachments/assets/4f64eca1-0f4e-4785-aa98-8c74aabc97ca)

The latest version of ps2sdk is not compatible with this compilation.

### Console model

77006

### Where do you have the issue?

FreeMcBoot

### Program version (if possible, also provide hash seen on installer used)

1.966

**Comment by israpps** [comment]
Latest SDK is not compatible with the FreeMcBoot installers.

It would be a waste of time doing so. It compiles with docker image `ps2dev/ps2dev:v1.0` as stated on the compilation script located at `.github/workflows/`

If you're looking for a latest SDK compatible program, take a look at [KELFBinder](GitHub.com/israpps/KELFBinder)

**Comment by xbox1978** [comment]
> Latest SDK is not compatible with the FreeMcBoot installers.
> 
> It would be a waste of time doing so. It compiles with docker image `ps2dev/ps2dev:v1.0` as stated on the compilation script located at `.github/workflows/`
> 
> If you're looking for a latest SDK compatible program, take a look at [KELFBinder](GitHub.com/israpps/KELFBinder)

I always fail, but I have translated the source code Lang.c . Could you help me compile it? Thanks a lot! Source code translation address: https://drive.google.com/file/d/1SlfxEj4ta7QPW2roPKTERutprBVIL5j8/view?usp=sharing

**Comment by israpps** [comment]
If you're not familiar with docker, you'll struggle less just by
1. forking this repository
2. making changes you want into your fork
3. Letting the CI compile it for you (on new forks, you might need to manually allow workflow trigger from the "actions" tab)

**Comment by xbox1978** [comment]
> If you're not familiar with docker, you'll struggle less just by
> 
> 1. forking this repository
> 2. making changes you want into your fork
> 3. Letting the CI compile it for you (on new forks, you might need to manually allow workflow trigger from the "actions" tab)

It would be nice if I could make a FreeMcBoot-Installer source code that can adapt to the latest version of ps2sdk. I hope it can be compiled in a real Ubuntu environment, just as easy as compiling Open-PS2-Loader. I guess no one has done it yet.

**Comment by israpps** [comment]
> > If you're not familiar with docker, you'll struggle less just by
> > 
> > 1. forking this repository
> > 2. making changes you want into your fork
> > 3. Letting the CI compile it for you (on new forks, you might need to manually allow workflow trigger from the "actions" tab)
> 
> It would be nice if I could make a FreeMcBoot-Installer source code that can adapt to the latest version of ps2sdk. I hope it can be compiled in a real Ubuntu environment, just as easy as compiling Open-PS2-Loader. I guess no one has done it yet.

Doing that is a waste of time.

Updating to latest SDK means you have to solve a shitton of bugs/compilation issues, most likely just to get a black screen.

Not to mention, that I also skipped that idea to avoid people claiming my custom installers are worse than the original onea

**Comment by xbox1978** [comment]
> > > If you're not familiar with docker, you'll struggle less just by
> > > 
> > > 1. forking this repository
> > > 2. making changes you want into your fork
> > > 3. Letting the CI compile it for you (on new forks, you might need to manually allow workflow trigger from the "actions" tab)
> > 
> > 
> > It would be nice if I could make a FreeMcBoot-Installer source code that can adapt to the latest version of ps2sdk. I hope it can be compiled in a real Ubuntu environment, just as easy as compiling Open-PS2-Loader. I guess no one has done it yet.
> 
> Doing that is a waste of time.
> 
> Updating to latest SDK means you have to solve a shitton of bugs/compilation issues, most likely just to get a black screen.
> 
> Not to mention, that I also skipped that idea to avoid people claiming my custom installers are worse than the original onea

It would be nice to have an Ubuntu image with an integrated compilation environment. I use this method to put the Ubuntu image with an integrated environment on a USB drive or a virtual machine and compile it directly in Windows. It is convenient and practical

**Comment by israpps** [comment]
Use docker then

**Comment by xbox1978** [comment]
> Use docker then

![Image](https://github.com/user-attachments/assets/561f1020-8627-416f-ac5a-72f2acea5bd2)
![Image](https://github.com/user-attachments/assets/bc8ffba6-50e0-46e8-89ce-0f5b6d3601dd)

No, first deploy the corresponding compiled program of the environment group on the real Ubuntu, for example, install the corresponding FreeMcBoot-Installer environment into Ubuntu, you can directly compile FreeMcBoot-Installer. Then back it up and encapsulate it into something like WindowsPE.ISO. It can be written to a USB drive and can be compiled and modified at any time. It is convenient and simple. Docker cannot be used normally in my area

**Comment by israpps** [comment]
Docker is the only available ready to use option for SDK version prior to newlib port.

It's accesible, even if you can't use docker directly, there's still GitHub actions that can do it for you.

I don't have the knowledge nor the time to do what you ask right now.
